<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
	<name>aeb</name>
	<version>0.0.0</version>
	<description>Automatic Emergency Braking (AEB) node for F1TENTH using LiDAR and odometry data.</description>

	<maintainer email="sriram.yerramsetty1@gmail.com">Sriram Yerramsetty</maintainer>
	<license>MIT</license>

	<buildtool_depend>ament_python</buildtool_depend>

	<exec_depend>rclpy</exec_depend>
	<exec_depend>sensor_msgs</exec_depend>
	<exec_depend>nav_msgs</exec_depend>
	<exec_depend>ackermann_msgs</exec_depend>
	<exec_depend>python3-numpy</exec_depend>

	<test_depend>ament_lint_auto</test_depend>
	<test_depend>ament_lint_common</test_depend>

	<export>
		<build_type>ament_python</build_type>
	</export>
</package>
